identifier: l7lbgcpdn4hd64t2
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: portfolio
homeFolder: C:\Users\Administrator\OneDrive\Documents\DEVELOPING\Angular\portfolio
distFolder: ./dist/portfolio
outDir: >-
  C:\Users\Administrator\OneDrive\Documents\DEVELOPING\Angular\portfolio\dist\static
handle404: ''
allowErrorCollect: true
